import {
  Smartphone,
  Shirt,
  Home,
  Gamepad2,
  Book,
  Watch,
  Baby,
  Camera,
  Car,
  Dumbbell,
  Gem,
  Music,
} from "lucide-react";

import retrGaming from "../assets/retro-gaming-console.png"
import vintageEle from "../assets/vintage-electronics.png"

export const quickCategories = [
  {
    name: "Fashion",
    icon: Shirt,
    color: "bg-pink-100",
    iconColor: "text-pink-600",
  },
  {
    name: "Electronics",
    icon: Smartphone,
    color: "bg-blue-100",
    iconColor: "text-blue-600",
  },
  {
    name: "Home",
    icon: Home,
    color: "bg-green-100",
    iconColor: "text-green-600",
  },
  {
    name: "Gaming",
    icon: Gamepad2,
    color: "bg-purple-100",
    iconColor: "text-purple-600",
  },
  {
    name: "Books",
    icon: Book,
    color: "bg-orange-100",
    iconColor: "text-orange-600",
  },
  {
    name: "Watches",
    icon: Watch,
    color: "bg-red-100",
    iconColor: "text-red-600",
  },
];

export const categories = [
  {
    name: "Electronics",
    icon: Smartphone,
    color: "bg-blue-100",
    iconColor: "text-blue-600",
    itemCount: 1247,
    description: "Phones, laptops, cameras, and more tech treasures",
    trending: true,
  },
  {
    name: "Fashion & Clothing",
    icon: Shirt,
    color: "bg-pink-100",
    iconColor: "text-pink-600",
    itemCount: 2156,
    description: "Vintage clothing, designer pieces, and accessories",
    trending: true,
  },
  {
    name: "Home & Living",
    icon: Home,
    color: "bg-green-100",
    iconColor: "text-green-600",
    itemCount: 892,
    description: "Furniture, decor, kitchenware, and home essentials",
    trending: false,
  },
  {
    name: "Gaming",
    icon: Gamepad2,
    color: "bg-purple-100",
    iconColor: "text-purple-600",
    itemCount: 634,
    description: "Consoles, games, controllers, and gaming accessories",
    trending: true,
  },
  {
    name: "Books & Media",
    icon: Book,
    color: "bg-orange-100",
    iconColor: "text-orange-600",
    itemCount: 1543,
    description: "Books, magazines, DVDs, and educational materials",
    trending: false,
  },
  {
    name: "Watches & Jewelry",
    icon: Watch,
    color: "bg-red-100",
    iconColor: "text-red-600",
    itemCount: 456,
    description: "Vintage watches, jewelry, and luxury accessories",
    trending: false,
  },
  {
    name: "Automotive",
    icon: Car,
    color: "bg-gray-100",
    iconColor: "text-gray-600",
    itemCount: 234,
    description: "Car parts, accessories, and automotive tools",
    trending: false,
  },
  {
    name: "Musical Instruments",
    icon: Music,
    color: "bg-yellow-100",
    iconColor: "text-yellow-600",
    itemCount: 189,
    description: "Guitars, keyboards, drums, and audio equipment",
    trending: false,
  },
  {
    name: "Photography",
    icon: Camera,
    color: "bg-indigo-100",
    iconColor: "text-indigo-600",
    itemCount: 312,
    description: "Cameras, lenses, tripods, and photo accessories",
    trending: true,
  },
  {
    name: "Collectibles",
    icon: Gem,
    color: "bg-teal-100",
    iconColor: "text-teal-600",
    itemCount: 567,
    description: "Rare items, antiques, and collector's pieces",
    trending: false,
  },
  {
    name: "Baby & Kids",
    icon: Baby,
    color: "bg-rose-100",
    iconColor: "text-rose-600",
    itemCount: 423,
    description: "Toys, clothes, strollers, and children's items",
    trending: false,
  },
  {
    name: "Sports & Fitness",
    icon: Dumbbell,
    color: "bg-emerald-100",
    iconColor: "text-emerald-600",
    itemCount: 298,
    description: "Exercise equipment, sports gear, and outdoor items",
    trending: false,
  },
];

export const popularCategories = [
  {
    name: "Fashion & Clothing",
    icon: Shirt,
    color: "bg-pink-100",
    iconColor: "text-pink-600",
    itemCount: 2156,
    weeklyGrowth: "+23%",
    image: vintageEle,
  },
  {
    name: "Electronics",
    icon: Smartphone,
    color: "bg-blue-100",
    iconColor: "text-blue-600",
    itemCount: 1247,
    weeklyGrowth: "+18%",
    image: vintageEle,
  },
  {
    name: "Gaming",
    icon: Gamepad2,
    color: "bg-purple-100",
    iconColor: "text-purple-600",
    itemCount: 634,
    weeklyGrowth: "+31%",
    image: retrGaming
  },
];
