import vintageClothStore from "../assets/vintage-clothing-store.png"
import homeDecorThrift from "../assets/home-decor-thrift-store.png"
import timeless from "../assets/timeless.png"
import retro from "../assets/retroStore.png"
import books from "../assets/usedBooksStore.png"


export const shops = [
    {
      name: "Vintage Vibes Boutique",
      location: "Downtown District",
      rating: 4.8,
      reviews: 324,
      image: vintageClothStore,
      specialties: ["Fashion & Clothing", "Accessories", "Vintage Jewelry"],
      description: "Curated vintage fashion from the 60s to 90s with authentic designer pieces",
      isOpen: true,
      phone: "(555) 123-4567",
      website: "vintagevibes.com",
      featured: true,
    },
    {
      name: "Tech Treasures",
      location: "Silicon Valley",
      rating: 4.6,
      reviews: 189,
      image: timeless,
      specialties: ["Electronics", "Gaming", "Photography"],
      description: "Refurbished electronics, retro gaming consoles, and camera equipment",
      isOpen: true,
      phone: "(555) 234-5678",
      website: "techtreasures.com",
      featured: false,
    },
    {
      name: "Home Sweet Thrift",
      location: "Suburban Plaza",
      rating: 4.7,
      reviews: 267,
      image: homeDecorThrift,
      specialties: ["Home & Living", "Furniture", "Kitchenware"],
      description: "Quality furniture, home decor, and kitchen essentials for every budget",
      isOpen: false,
      phone: "(555) 345-6789",
      website: "homesweetthrift.com",
      featured: true,
    },
    {
      name: "Bookworm's Paradise",
      location: "University District",
      rating: 4.9,
      reviews: 412,
      image: books,
      specialties: ["Books & Media", "Educational", "Collectibles"],
      description: "Rare books, textbooks, vinyl records, and literary treasures",
      isOpen: true,
      phone: "(555) 456-7890",
      website: "bookwormsparadise.com",
      featured: false,
    },
    {
      name: "Retro Gaming Hub",
      location: "Entertainment District",
      rating: 4.5,
      reviews: 156,
      image: retro,
      specialties: ["Gaming", "Electronics", "Collectibles"],
      description: "Classic consoles, vintage games, and gaming memorabilia from all eras",
      isOpen: true,
      phone: "(555) 567-8901",
      website: "retrogaminghub.com",
      featured: false,
    },
    {
      name: "Timeless Treasures",
      location: "Historic Quarter",
      rating: 4.8,
      reviews: 298,
      image: timeless,
      specialties: ["Watches & Jewelry", "Collectibles", "Antiques"],
      description: "Authentic vintage watches, fine jewelry, and precious collectibles",
      isOpen: false,
      phone: "(555) 678-9012",
      website: "timelesstreasures.com",
      featured: true,
    },
  ]